### ISSUE TITLE
Broken link in the article (Performance Benchmark Analysis of Egress Filtering on Linux)

### ISSUE THREAD

**Issue by spiarh** [kinvolk/egress-filtering-benchmark#19]
**Description**

Thanks for the [article (Performance Benchmark Analysis of Egress Filtering on Linux)](https://kinvolk.io/blog/2020/09/performance-benchmark-analysis-of-egress-filtering-on-linux/), it's a very interesting read!

The **own** link in the following sentence points to `https://github.com/kinvolk/egress-filtering-benchmark/blob/master/pkg/filters/bpf/datapath/bpf.c` which returns **404**.

> Given that we want to keep the tests as simple as possible we decided to implement our own filtering program in eBPF that will be attached to the traffic control layer with a clsact qdisc.

I assume the correct one is: `https://github.com/kinvolk/egress-filtering-benchmark/blob/master/pkg/filters/tc-bpf/datapath/bpf.c`

**Comment by mauriciovasquezbernal** [comment]
@lcavajani the link is now fixed. Thanks a lot for the report!
